AUG:
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  COLOR_JITTER: 0.4
  ENABLE: true
  INTERPOLATION: bicubic
  NUM_SAMPLE: 1
  RE_COUNT: 1
  RE_MODE: pixel
  RE_PROB: 0.25
  RE_SPLIT: false
BN:
  NUM_BATCHES_PRECISE: 200
  USE_PRECISE_STATS: false
DATA:
  DECODING_BACKEND: torchvision
  INPUT_CHANNEL_NUM:
  - 3
  NUM_FRAMES: 16
  PATH_PREFIX: /home/datasets/smthsmth/frames
  PATH_TO_DATA_DIR: /home/datasets/
  RANDOM_FLIP: false
  SAMPLING_RATE: 2
  TEST_CROP_SIZE: 224
  TRAIN_CROP_SIZE: 224
  TRAIN_JITTER_ASPECT_RELATIVE:
  - 0.75
  - 1.3333
  TRAIN_JITTER_SCALES:
  - 256
  - 320
  TRAIN_JITTER_SCALES_RELATIVE:
  - 0.08
  - 1.0
  USE_OFFSET_SAMPLING: true
DATA_LOADER:
  NUM_WORKERS: 7
  PIN_MEMORY: true
DDP_FIND_UNUSED_PARAMETERS: false
IMAGE_TRAIN:
  BATCH_SIZE: 63
  DATASETS:
  - ssv2_frames
  GPU_IDS:
  - 7
MIXUP:
  ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  ENABLE: false
  LABEL_SMOOTH_VALUE: 0.1
  PROB: 1.0
  SWITCH_PROB: 0.5
MODEL:
  ARCH: mvit
  DROPOUT_RATE: 0.5
  LOSS_FUNC: video_image_loss
  MODEL_NAME: SViT
  NUM_CLASSES: 174
MVIT:
  CLS_EMBED_ON: true
  DEPTH: 16
  DIM_MUL:
  - - 1
    - 2.0
  - - 3
    - 2.0
  - - 14
    - 2.0
  DIM_MUL_IN_ATT: true
  DROPOUT_RATE: 0.0
  DROPPATH_RATE: 0.4
  EMBED_DIM: 96
  HEAD_MUL:
  - - 1
    - 2.0
  - - 3
    - 2.0
  - - 14
    - 2.0
  MLP_RATIO: 4.0
  MODE: conv
  NORM: layernorm
  NUM_HEADS: 1
  PATCH_KERNEL: (3, 7, 7)
  PATCH_PADDING: (1, 3, 3)
  PATCH_STRIDE: (2, 4, 4)
  POOL_KVQ_KERNEL:
  - 3
  - 3
  - 3
  POOL_KV_STRIDE_ADAPTIVE:
  - 1
  - 8
  - 8
  POOL_Q_STRIDE:
  - - 0
    - 1
    - 1
    - 1
  - - 1
    - 1
    - 2
    - 2
  - - 2
    - 1
    - 1
    - 1
  - - 3
    - 1
    - 2
    - 2
  - - 4
    - 1
    - 1
    - 1
  - - 5
    - 1
    - 1
    - 1
  - - 6
    - 1
    - 1
    - 1
  - - 7
    - 1
    - 1
    - 1
  - - 8
    - 1
    - 1
    - 1
  - - 9
    - 1
    - 1
    - 1
  - - 10
    - 1
    - 1
    - 1
  - - 11
    - 1
    - 1
    - 1
  - - 12
    - 1
    - 1
    - 1
  - - 13
    - 1
    - 1
    - 1
  - - 14
    - 1
    - 2
    - 2
  - - 15
    - 1
    - 1
    - 1
  QKV_BIAS: true
  REL_POS_SPATIAL: true
  REL_POS_TEMPORAL: true
  RESIDUAL_POOLING: true
  USE_ABS_POS: false
  ZERO_DECAY_POS_CLS: false
NUM_GPUS: 8
NUM_SHARDS: 1
OUTPUT_DIR: .
RNG_SEED: 0
SOLVER:
  BASE_LR: 2e-4
  BASE_LR_SCALE_NUM_SHARDS: true
  CLIP_GRAD_L2NORM: 1.0
  COSINE_AFTER_WARMUP: true
  COSINE_END_LR: 2e-6
  LR_POLICY: cosine
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  OPTIMIZING_METHOD: adamw
  WARMUP_EPOCHS: 0.0
  WARMUP_START_LR: 2e-6
  WEIGHT_DECAY: 0.0001
  ZERO_WD_1D_PARAM: true
SSV2:
  SPLIT: standard
SVIT:
  LAMBDA_CON: 1.5
  LAMBDA_EDGES: 0.3
  LAMBDA_NODES: 3.7
TEST:
  BATCH_SIZE: 64
  DATASET: ssv2
  ENABLE: true
  NUM_SPATIAL_CROPS: 3
TRAIN:
  AUTO_RESUME: true
  BATCH_SIZE: 63
  CHECKPOINT_EPOCH_RESET: true
  CHECKPOINT_FILE_PATH: "" # Path to pretrained
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_TYPE: pytorch
  DATASET: ssv2
  ENABLE: true
  EVAL_PERIOD: 5
  MIXED_PRECISION: true
